name: Laravel-docker

on:
  push:
    branches: [ "main" ]
    
  workflow_dispatch:

jobs:
  laravel-docker:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag zhonghaibin/mm_php:1.0
      - name: Docker Login
        uses: docker/login-action@v2.2.0
        with:
            username: ${{secrets.DOCKER_USERNAME}}
            password: ${{secrets.DOCKER_PASSWORD}}
      - name: Push Docker images
        run: docker push  zhonghaibin/mm_php:1.0
        
      - name: SSH command
        uses: appleboy/ssh-action@v0.1.10
        with:
            host: ${{secrets.NAS_HOST}}
            username: ${{secrets.NAS_USERNAME}}
            port: ${{secrets.NAS_PORT}}
            password: ${{secrets.NAS_PASSWORD}}
            script: | # 重启更新镜像
               /usr/local/bin/docker pull zhonghaibin/mm_php:1.0
               /usr/local/bin/docker stop mm_php
               /usr/local/bin/docker rm mm_php
               /usr/local/bin/docker run --name=mm_php -d -p 8000:8000  zhonghaibin/mm_php:1.0
               /usr/local/bin/docker cp /volume1/docker/web/mm_php/.env mm_php:/app
               
